app:
  config:
    path: src/resources/appclient.yaml
  chain:
    name: mychain1
  channel:
    name: testchannel2017
  chaincode:
    name: example_go
    version: 1
    path: github.com/example
    intantiation:
      fnc: Init
      args: testuser,1000,1